apiVersion: v1
kind: Pod
metadata:
  name: mongo
  labels:
    app: mongo
spec:
  containers:
  - name: mongo
    image: mongo
    ports:
    - containerPort: 27017
    env:
      - name: AUTH
        valueFrom:
          configMapKeyRef:
            name: mongodb-config
            key: AUTH
      - name: MONGODB_INITDB_ROOT_USERNAME
        valueFrom:
          configMapKeyRef:
            name: mongodb-config
            key: MONGODB_INITDB_ROOT_USERNAME
      - name: MONGODB_INITDB_ROOT_PASSWORD
        valueFrom:
          configMapKeyRef:
            name: mongodb-config
            key: MONGODB_INITDB_ROOT_PASSWORD
      - name: MONGODB_INITDB_DATABASE
        valueFrom:
          configMapKeyRef:
            name: mongodb-config
            key: MONGODB_INITDB_DATABASE
