apiVersion: v1
kind: Pod
metadata:
  name: order-manager
  labels:
    app: order-manager
spec:
  containers:
  - name: order-manager
    image: jeansbs/order_manager:1.0
    ports:
    - containerPort: 3000
    env:
      - name: MONGO_CONNECTION_STRING
        valueFrom:
          configMapKeyRef:
            name: order-manager-config
            key: MONGO_CONNECTION_STRING
