apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-order-manager
  labels:
    name: pv-order-manager
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-storage
  hostPath:
    path: /run/desktop/mnt/host/c/Users/jeans/automacao/nest/pos/data
