### Get All Customers
GET http://localhost:3000/customer

### Get Customer By ID
GET http://localhost:3000/customer/id/659c85f6a875970be57aa7c5

### Get Customer by CPF
GET http://localhost:3000/customer/cpf/1234

### Create Customer
POST http://localhost:3000/customer
Content-Type: application/json

{
    "email": "Jean_CanetaAzul@non_validprovider.com",
    "cpf": "35690685600",
    "name": "Jean Caneta Azul"
}

### Update Customer
PUT http://localhost:3000/customer/659c85f6a875970be57aa7c5
Content-Type: application/json

{
    "email": "jean_canetaazul@anothervalidprovider.com"
}

### Delete Customer
DELETE http://localhost:3000/customer/659c85f6a875970be57aa7c5

### Get All Orders
GET http://localhost:3000/orders

### Get All Products
GET http://localhost:3000/products


### Get Product By Category
GET http://localhost:3000/products/category/lanche


### Create Product
POST http://localhost:3000/products
Content-Type: application/json

{     
    "name": "Coca",
    "category": "bebida",
    "value": 10.5,
    "quantity": 1,
    "description": "Uma bebidinha gelada Majin Boo hi hi hi" 
}

### Delete Product
DELETE http://localhost:3000/products/659f13ebef543bf514d22b5d

